# Generated by Django 6.0.7 on 2026-07-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=20, unique=True)),
                ('license_category', models.CharField(choices=[('LMV', 'Light Motor Vehicle'), ('HMV', 'Heavy Motor Vehicle'), ('HTV', 'Heavy Transport Vehicle'), ('HGMV', 'Heavy Goods Motor Vehicle')], max_length=10)),
                ('license_expiry', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('safety_score', models.PositiveIntegerField(default=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_trip', 'On Trip'), ('on_leave', 'On Leave'), ('suspended', 'Suspended')], default='available', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='drivers/')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
