# Generated by Django 6.0.7 on 2026-07-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='license_document',
            field=models.FileField(blank=True, help_text='Upload driving license (Image or PDF)', null=True, upload_to='licenses/'),
        ),
    ]
