# Generated by Django 6.0.7 on 2026-07-12 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_license_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_document',
            field=models.FileField(blank=True, help_text='Upload driving license (Image or PDF)', null=True, upload_to='licenses/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 15-character Indian driving license number (e.g., MH1420110062821)', regex='^[A-Z]{2}[0-9]{2}[0-9]{11}$')]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must contain only letters and spaces.', regex='^[a-zA-Z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='safety_score',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
