# Generated by Django 6.0.7 on 2026-07-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('van', 'Van'), ('bus', 'Bus'), ('pickup', 'Pickup'), ('tanker', 'Tanker')], default='truck', max_length=20)),
                ('capacity', models.DecimalField(decimal_places=2, help_text='Max load in tons', max_digits=10)),
                ('current_odometer', models.PositiveIntegerField(default=0, help_text='Odometer in km')),
                ('acquisition_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_trip', 'On Trip'), ('in_shop', 'In Shop'), ('retired', 'Retired')], default='available', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
