# Generated by Django 6.0.7 on 2026-07-12 05:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rc_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='capacity',
            field=models.DecimalField(decimal_places=2, help_text='Max load in tons', max_digits=10, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='current_odometer',
            field=models.PositiveIntegerField(default=0, help_text='Odometer in km', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Indian vehicle registration number (e.g. MH01AB1234)', regex='^[A-Z]{2}[0-9]{2}[A-Z]{1,2}[0-9]{4}$')]),
        ),
    ]
